export const services = [
  {
    name: "Classic Manicure",
    time: 20,
    price: 30,
    category: "manicure",
    details: "Classic Manicure details goes gere",
  },
  {
    name: "Nail Extension",
    time: 50,
    price: 60,
    category: "manicure",
    details: "Nail Extension details goes gere",
  },
  {
    name: "Deluxe Manicure",
    time: 30,
    price: 40,
    category: "manicure",
    details: "Deluxe Manicure details goes gere",
  },
  {
    name: "Mani-Pedi",
    time: 40,
    price: 60,
    category: "pedicure",
    details: "Mani-Pedi details goes gere",
  },
  {
    name: "Classic Pedicure",
    time: 20,
    price: 15,
    category: "pedicure",
    details: "Classic Pedicure details goes gere",
  },
  {
    name: "Medical Pedi",
    time: 45,
    price: 50,
    category: "pedicure",
    details: "Medical Pedi details goes gere",
  },
  {
    name: "Gel Polish Removal",
    time: 15,
    price: 10,
    category: "gel-polish",
    details: "Gel Polish Removal details goes gere",
  },
  {
    name: "Gel Polish Manicure",
    time: 45,
    price: 50,
    category: "gel-polish",
    details: "Gel Polish Manicure details goes gere",
  },
  {
    name: "Custom Design",
    time: 60,
    price: 80,
    category: "nail-art",
    details: "Custom Design details goes gere",
  },
];
