class JobSerializer < ActiveModel::Serializer
  attributes :id,
            :user,
            :pick_up_date,
            :delivery_date,
            :start_time,
            :job_status,
            :job_size,
            :job_type,
            :crew_size,
            :job_rate,
            :crew,
            :estimated_time,
            :travel_time,
            :estimated_quote,
            :additional_info,
            :job_duration,
            :total_amount,
            :created_at,
            :updated_at,
            :origin,
            :destination,
            :images
end
